name: Build

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: build-ts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install-dependencies
      run: npm install
    - name: delete-current-build
      run: rm -rf dist
    - name: build
      run: npm run build